### ISSUE TITLE
It would be nice to weave "Lifecycle pre and post deployment hooks" into the main section

### ISSUE THREAD

**Issue by brenton** [openshift/training#113]
Right now it's only an appendix.  That's better than nothing.  My only concern is that it's so long it might complicate the flow of the rest of the training.

**Comment by thoraxe** [comment]
I think we should probably add it to the existing wiring example, since we're already using it as a "catch-all" for several other things (deployment, rollback, etc).

Additionally, since we also are "requiring" people to fork the repo to do the rollback/activate examples they already have a fork that they can easily add the new table and hook-y stuff too.

I'll probably make an attempt to "do it live" during the training recording, and then go back and modify the material to better weave it in.

**Comment by thoraxe** [comment]
Closed by #147
