### ISSUE TITLE
ansible firewall blocks port 53 on nodes

### ISSUE THREAD

**Issue by cgwalters** [openshift/training#289]
I was using the example of dnsmasq on node0, but the Ansible playbooks set up a firewall rule which blocks port 53.

One option is:

```
diff --git a/roles/openshift_node/defaults/main.yml b/roles/openshift_node/defaults/main.yml
index be51195..1cae426 100644
--- a/roles/openshift_node/defaults/main.yml
+++ b/roles/openshift_node/defaults/main.yml
@@ -6,3 +6,7 @@ os_firewall_allow:
   port: 80/tcp
 - service: https
   port: 443/tcp
+- service: dnsudp
+  port: 53/udp
+- service: dnstcp
+  port: 53/tcp
```

But I think we should proabably recommend running DNS on a machine outside of the cluster entirely.

**Comment by thoraxe** [comment]
If the iptables rule is already in /etc/sysconfig/iptables it should not get blocked. If the rule is just hanging out in iptables' "memory" then it will get nuked after the installer runs.

Is this not what you're seeing?

**Comment by cgwalters** [comment]
I started these nodes without any firewalling enabled.

**Comment by cgwalters** [comment]
(They have OpenStack security groups in place rather than host based firewalls)

**Comment by thoraxe** [comment]
So I think the misunderstanding is around the term "block".

iptables is an absolute requirement for OpenShift v3's service layer to work. In order to do this, the installer sets up various firewall rules, but does not explicitly include a port 53 (dns) rule.

If you want to run DNS inside the OpenShift "cluster", you would need to put the rule in your iptables configuration ahead of time.

I think that the real issue you're describing is something like:

*When I don't have iptables preconfigured in any way the resulting Ansible firewall configuration may close off the DNS port".

I don't really know of a good way to deal with that other than adding a special flag to Ansible to ensure that DNS (port 53) is open on the host(s), but you would need to file that as an issue against the installer.

I'm going to close this issue because it's not directly related to the training material, and I think it also represents an edge case that I'm not sure we want to add the complexity of handling in the installer. But that's up to those guys :)
