### ISSUE TITLE
add port documentation link

### ISSUE THREAD

**Issue by VeerMuchandi** [openshift/training#291]
On IaaS deployments such as OS1, we will need the list of ports to be opened in security groups. Please add the complete list in this section as a prerequisite. I am using the following list. Please verify and add the list

TCP 22 (SSH)  
TCP 53 (DNS)  
TCP 80 (HTTP)  
TCP 443 (HTTPS) 
TCP 1936  
TCP 4001  
TCP 7001  
TCP 8443 - 8444 
TCP 10250  
TCP 24224  
UDP 53  
UDP 4789  
UDP 24224

**Comment by thoraxe** [comment]
This is pending resolution of https://github.com/openshift/openshift-docs/issues/684 . It won't be directly included, but will rather link to whatever the official docs become.

**Comment by Miciah** [comment]
@VeerMuchandi, do we really need 24224? A quick search tells me that 24224 is for fluentd, which we aren't using right now.  Also, do we need 8444? We used that for the console before 1.0, but we have since put the console on 8443 (sharing the port with the apiserver), so we shouldn't still need 8444 open.

As for the others,
- TCP 22 (SSH) is needed by the installer or for the sysadmin to use but is not needed by OpenShift itself.
- UDP/TCP 53 (DNS) is for SkyDNS, so it only needs to be internally open on masters.
- TCP 80/443 (HTTP/HTTPS) are for the router, so they need to be externally open on nodes (specifically on nodes that are running the router—if you put your routers in a specially labelled collection of infrastructure nodes, then you only need these ports open on those nodes).
- TCP 1936 is for router stats, so it only needs to be open if you are using the template router and need access to its stats, it only needs to be open where you are running the router, and it can be open to external or internal connections depending on whether or not you want the stats exposed publicly.
- TCP 4001/7001 are for etcd, so they only need to be internally open on the master.  Port 4001 is for server-client connections whereas port 7001 is for server-server connections, so the latter is not required unless you have clustered etcd.
- TCP 4789 is for VxLAN (OpenShift SDN), so it only needs to be internally open on nodes.
- TCP 8443 is for the apiserver and the console, so it only needs to be open on masters, externally for the console and internally for the apiserver.
- TCP 10250 is for kubelet, so it needs to be internally open on nodes.

**Comment by thoraxe** [comment]
@Miciah the current openshift-ansible master installs fluentd...

**Comment by Miciah** [comment]
Cool! So it looks like port 24224 needs to be open on masters to internal connections from nodes.

**Comment by detiber** [comment]
@Miciah @thoraxe is that the case for all deployment types, last I was aware, we are only enabling fluentd for "online" deployments (though we are opening the firewall port on the host on all deployment types).

**Comment by thoraxe** [comment]
@detiber I can't understand in the playbooks where that determination is actually made. I thought I had seen fluentd installed around the beta4 timeframe, but perhaps that's been backed out?

**Comment by detiber** [comment]
@thoraxe it is in the openshift_facts.py module in the openshift_facts role.  There is an upstream PR to enable/disable fluentd for all deployment_types here: https://github.com/openshift/openshift-ansible/pull/459

**Comment by nak3** [comment]
Can you close this issue? We have already the doc - https://docs.openshift.com/enterprise/3.2/install_config/install/prerequisites.html#prereq-network-access

**Comment by thoraxe** [comment]
Well, the issue is about "adding the link", so the link you provided might be the link in question.

That being said this repo (training) is going away in the next few months as we move to https://github.com/openshift/discoverycenter
