### ISSUE TITLE
osc probably needs its own .kubeconfig

### ISSUE THREAD

**Issue by brenton** [openshift/training#31]
Right now the ansible installer is setting KUBECONFIG=/var/lib/openshift/openshift.local.certificates/admin/.kubeconfig in .bash_profile.  The problem with this is when we change the default context things start to break.  Namely, the ansible node registration process will break because it will attempt to use the `demo` context.

**Comment by thoraxe** [comment]
Someone said we can put a kubeconfig into ~ and that would work (and not get rewritten)... so should we just have the installer NOT do anything with bash_profile?

I guess I don't completely understand the failure here.

**Comment by brenton** [comment]
I haven't looked a lot at how the ansible tooling is registering Nodes but I suspect it's using the kubeconfig on the master.  When I went through the docs it seemed that the only place osc was installed was on the master so I assumed that was where I was suppose to run the developer commands for creating apps etc.  When the instructions change the default context to demo if you then try to register nodes using that same .kubeconfig it will fail because the namespace will be wrong.

**Comment by brenton** [comment]
@detiber, let me know if this makes sense to you.

**Comment by thoraxe** [comment]
All the installer needs to do is:

create a `.kube` folder in root's home directory
copy `/var/lib/openshift/openshift.local.certificates/admin/.kubeconfig` into the `.kube` folder.

Then all the commands will JUSTWORK (tm).

**Comment by thoraxe** [comment]
See:
https://github.com/openshift/training/blame/master/beta-2-setup.md#L219

**Comment by detiber** [comment]
The v3-beta2 branch of detiber/openshift-ansible has been updated. Now it no longer sets the KUBECONFIG env variable, instead it copies the admin kubeconfig to ~/.kube/.kubeconfig for the root user.

Also, I updated how the registration is done, now instead of just relying on the environment/user config, it will query the config and set the --user, --context, and --cluster options using the defaults (admin, master, and master respectively).

There is still an outstanding issue: https://github.com/detiber/openshift-ansible/issues/4, where the ansible task attempts to copy the kubeconfig before it has been created, but I believe the initial issue regarding node registration has been taken care of.

@brenton I see you mentioned namespace in one comment, I didn't see anything within `openshift ex config view` or in the .kubeconfig referring to namespace, did you mean context instead? If needed I can update the openshift_register_node module to use a default namespace as well.

The current workflow for registering a node is as follows:
- `openshift_node` playbook
  - `openshift_node` role
    - `openshift_register_node` module with name=<openshift_hostname> (client_user=admin, client_cluster=master, client_context=master, cpu=<num logical cpus>, memory=80% of free memory are supplied from the default values)
      - `openshift ex config view` to sanity check kubeconfig (verifies that context exists in contexts, user and cluster exist in context, overrides any of the values if they are not the default)
      - `osc create node` passing in the generated node definition
        - if create node returns failure and the text matches the text for a node already existing exit with changed=False
        - if create node returns successfully, exit with changed=True

As an aside, the 80% of free memory is probably the reason you are seeing uneven pod distribution @thoraxe. I'm thinking now we should default (and recommend) setting it to a default % of total memory instead.

**Comment by brenton** [comment]
@detiber, yeah, I meant context.

**Comment by thoraxe** [comment]
So, I am gonna close this one because my latest updates separate "non-admin" users out and they use ex login.

@detiber I agree - please make a configurable percentage of max mem for the installer, and let's default it to 75%. I will open an issue against installer for that.
