### ISSUE TITLE
Admin Training

### ISSUE THREAD

**Issue by kotarusv** [openshift/training#375]
Can you have a separate training guide tailored for admin and infra persons. Openshift Enterprise official documentation is very high level. It might be useful for reference but not suitable for learning to support and maintain the infrastructure. It would be nice keeping real world example and provide more insight into customization options on every aspect to suites to enterprise workloads

Srinivas Kotaru

**Comment by thoraxe** [comment]
There is a longer-term plan brewing where we will likely divide up a lot of these exercises into administrative, developer-focused as well as architect-focused exercises.

And, of course, PRs are welcome!

I'll close this particular issue because it's not explicitly actionable, but look for changes to come.
