### ISSUE TITLE
customized "action hook" that does something

### ISSUE THREAD

**Issue by thoraxe** [openshift/training#46]
it would be great if someone could write an sti build script that does something "Viewable/observable" to demonstrate an action hook.

**Comment by bparees** [comment]
I've created a version of ruby-hello that includes a custom assemble script here:
https://github.com/bparees/ruby-hello-world/tree/custom_sti

the custom assemble script adds an additional echo command:
https://github.com/bparees/ruby-hello-world/blob/custom_sti/.sti/bin/assemble#L48

you can use the repo/branch by updating the application-template-stibuild.json BuildConfig source to this:
        "source": {
          "git": {
            "uri": "git://github.com/bparees/ruby-hello-world.git",
            "ref": "custom_sti"
          },
          "type": "Git"
        },

notice the use of the "ref" field to point to the specific branch.

(obviously I recommend you create your own fork/branch)

you will notice in the build logs two things:
1) 2015-03-06T21:54:48.818206106Z I0306 21:54:48.818194       1 sti.go:181] Using assemble from upload/src/.sti/bin

which indicates it picked up the assemble script from the source repo instead of from the image.

2) the build-logs output will contain the modified output from the custom assemble script:
[2015-03-06T21:55:26.603110030Z] I0306 21:55:26.603090       1 sti.go:357] ---> CUSTOM STI ASSEMBLE COMPLETE

**Comment by bparees** [comment]
@thoraxe can we close this?

**Comment by thoraxe** [comment]
About to look at it right now.

**Comment by thoraxe** [comment]
Just merged a PR into the main sample app codebase, so now I need to test the example.

**Comment by thoraxe** [comment]
Documented for beta2. Thanks!
