### ISSUE TITLE
[beta2] Setup difficult getting DNS behaving

### ISSUE THREAD

**Issue by sspeiche** [openshift/training#63]
Not sure there is a specific bug or fix, this was just an area that I struggled with the most.  Perhaps due to VirtualBox, issues with wireless on Mac, iptables firewall port being blocked, etc.  Perhaps seasoned OpenShifters are used to all this but I spent a fairly significantly larger percentage of time on this than I feel like I should have.  With all the variables involved (host OS, VM software, etc) though it might be helpful to have a single "golden" configuration to reference.

**Comment by thoraxe** [comment]
Unfortunately there are too many config possibilities. The expectation is that most folks:

1) are using some kind of "real" virtualization solution (eg: KVM, VMWare, OpenStack, etc)
2) understand or have the ability to configure the networking components ahead of time

Most of the issues we've seen are related to people trying to use Virtualbox and not configuring its networking correctly, which results in very weird things happening because Virtualbox ends up not creating an actual real NATted network for the VMs to sit on.

I've personally never used Virtualbox, or Vagrant, but that seems to be a popular combination with some of our engineers. If anyone wants to submit a PR for an appendix on how to set this up wtih VB and/or Vagrant, that would be awesome.
