### ISSUE TITLE
need appendix for installation on AWS and similar

### ISSUE THREAD

**Issue by thoraxe** [openshift/training#84]

**Comment by thoraxe** [comment]
@detiber do you think you can do this on Monday?

**Comment by detiber** [comment]
@thoraxe I'll have something submitted today, was working on it Friday with plans to finish up over the weekend, but then my house contracted a nasty plague.

**Comment by detiber** [comment]
@thoraxe https://github.com/openshift/training/pull/139

**Comment by detiber** [comment]
I was hoping to also have route53 integration working so that the user could specify an app domain and a hosts domain and it would all just work, but ran into 2 issues.
1. The ansible route53 module doesn't support creating hosted zones
2. The route53 module had a bug where it wasn't accepting a wildcard record, so the app domain wouldn't work.

My hope is to get the work here integrated into openshift-ansible and eventually get the route53 stuff worked out as well.

**Comment by thoraxe** [comment]
so should this issue be closed or do you still have pending work?

**Comment by detiber** [comment]
@thoraxe as far as I know we are good to close this. As the changes get worked into the upstream ansible work, I'll submit PRs to update accordingly, but I would consider those separate issues.
